version: "3.9"

services:
    database:
        image: postgres
        container_name: database
        restart: always
        ports:
            - 1288:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=database
        volumes:
            - pgdata:/data/postgres


    app:
        build: .
        container_name: app_mks
        restart: always
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
